version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      PGAAS_DATASOURCE_URL: jdbc:postgresql://db:5432/main
      PGAAS_DATASOURCE_SERVER: db
      PGAAS_DATASOURCE_PORT: 5432
      PGAAS_DATASOURCE_DB: main
      PGAAS_DATASOURCE_USERNAME: user
      PGAAS_DATASOURCE_PASSWORD: pass

      SECONDARY_DB_SERVER: offer_db
      SECONDARY_DB_PORT: 5432
      SECONDARY_DB: secondary
      SECONDARY_DB_USER: user
      SECONDARY_DB_PASS: pass

      JWT_TOKEN: railolograilolograilolograilolograilolograilolog
      SERVER_PORT: 8080
    restart: on-failure
    depends_on:
      - db
      - offer_db

  db:
    image: postgres:16
    shm_size: 128mb
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/db1:/var/lib/postgresql/data

  offer_db:
    image: postgres:16
    shm_size: 128mb
    environment:
      POSTGRES_DB: secondary
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5433:5432"
    volumes:
      - ./postgres/offer_db:/var/lib/postgresql/data