version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/studs
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass
      SERVER_PORT: 8080
    restart: on-failure
    depends_on:
      - db

  db:
    image: postgres:16
    shm_size: 128mb
    environment:
      POSTGRES_DB: studs
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/db1:/var/lib/postgresql/data

#  db2:
#    image: postgres:12
#    environment:
#      POSTGRES_DB: mydatabase2
#      POSTGRES_USER: user2
#      POSTGRES_PASSWORD: pass2
#    ports:
#      - "5433:5432"